spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: yourPoolName
            auto-commit: false
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/rmdb
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource  
   
hibernate:
              dialect: org.hibernate.dialect.MySQLDialect
              